"""
Selects the 200 largest refactoring commits authored by distinct developers
between 2024 and 2026.

This script derives the study dataset from the refactoring dataset produced
by our previous study (`refactorings.parquet`). The selection process is:

1. Remove commits authored by GitHub bots.
2. Restrict commits to the 2024-2026 period.
3. Count the number of detected refactorings in each commit.
4. Select the commit with the largest number of refactorings for each author.
5. Rank authors by the size of their selected commit.
6. Keep the top 200 authors/commits.
7. Count Type Hint (TH) and Structural Pattern Matching (SPM) refactorings
   in the selected commits.
8. Export the resulting dataset to an Excel file.

The resulting dataset was used as the basis for the manual analysis of
large-scale refactoring commits reported in the study.
"""

import pandas as pd


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

# Input dataset generated by the previous study.
INPUT_FILE = "data/refactorings.parquet"

# Output file containing the selected commits.
OUTPUT_FILE = "data/top_200_ref_dev.xlsx"

# Columns included in the final dataset.
OUTPUT_COLUMNS = [
    "commit_url",
    "commit_time",
    "refactoring_count",
    "author_email",
    "TH_count",
    "SPM_count",
]


# ---------------------------------------------------------------------------
# Load dataset
# ---------------------------------------------------------------------------

df = pd.read_parquet(INPUT_FILE)

print(f"Loaded {len(df):,} refactorings from {INPUT_FILE}")


# ---------------------------------------------------------------------------
# Remove bot-authored commits
# ---------------------------------------------------------------------------
# GitHub bot accounts commonly use noreply.github.com addresses.
# These commits are excluded because the study focuses on human developers.

df = df[
    ~df["author_email"].str.contains(
        "noreply.github.com",
        case=False,
        na=False,
    )
].copy()

print(f"After excluding bots: {len(df):,} refactorings")


# ---------------------------------------------------------------------------
# Count refactorings per commit
# ---------------------------------------------------------------------------
# Each row in the input dataset represents a detected refactoring.
# Therefore, counting rows for each commit gives the total number of
# refactorings detected in that commit.

commit_sizes = (
    df.groupby(
        ["repository", "commit", "commit_time", "author_email"],
        as_index=False,
    )
    .size()
    .rename(columns={"size": "refactoring_count"})
)


# ---------------------------------------------------------------------------
# Restrict the analysis to 2024-2026
# ---------------------------------------------------------------------------
# The study focuses on recent large-scale refactoring activity.
# The lower bound is January 1, 2024.

commit_sizes["year"] = commit_sizes["commit_time"].dt.year

commit_sizes = commit_sizes[
    commit_sizes["year"].between(2024, 2026)
].copy()

print(
    f"Commits from 2024-2026: {len(commit_sizes):,}"
)


# ---------------------------------------------------------------------------
# Select the largest commit for each developer
# ---------------------------------------------------------------------------
# To obtain one representative large-scale commit per developer,
# we select the commit containing the largest number of refactorings
# authored by each developer.

largest_commit_per_author = commit_sizes.loc[
    commit_sizes.groupby("author_email")["refactoring_count"].idxmax()
].copy()

largest_commit_per_author = largest_commit_per_author.sort_values(
    "refactoring_count",
    ascending=False,
)

print(
    f"Unique authors with qualifying commits: "
    f"{largest_commit_per_author['author_email'].nunique():,}"
)


# ---------------------------------------------------------------------------
# Select the top 200 developers
# ---------------------------------------------------------------------------
# The 200 authors whose selected commits contain the largest number of
# refactorings constitute the candidate set for the subsequent analysis.

top_200 = largest_commit_per_author.head(200).copy()

# Sort the selected commits by date for easier inspection.
top_200 = top_200.sort_values(
    "commit_time",
    ascending=False,
).copy()


# ---------------------------------------------------------------------------
# Build GitHub commit URLs
# ---------------------------------------------------------------------------
# The repository field contains the repository URL and the commit field
# contains the commit SHA.

top_200["commit_url"] = (
    top_200["repository"].str.replace(
        ".git",
        "/commit/",
        regex=False,
    )
    + top_200["commit"]
)


# ---------------------------------------------------------------------------
# Identify Type Hint and Structural Pattern Matching refactorings
# ---------------------------------------------------------------------------
# The input dataset contains the detected refactoring type for each row.
# We create boolean indicators for refactorings related to:
#
#   TH  = Type Hints
#   SPM = Structural Pattern Matching

df["TH"] = df["type"].str.contains(
    "Type Annotation",
    na=False,
)

df["SPM"] = df["type"].str.contains(
    "Pattern Matching",
    na=False,
)


# Count TH and SPM refactorings for each commit.
commit_types = (
    df.groupby(
        ["repository", "commit"],
        as_index=False,
    )
    .agg(
        TH_count=("TH", "sum"),
        SPM_count=("SPM", "sum"),
    )
)


# ---------------------------------------------------------------------------
# Add refactoring-type counts to the selected commits
# ---------------------------------------------------------------------------

top_200 = top_200.merge(
    commit_types,
    on=["repository", "commit"],
    how="left",
)

# Commits without TH/SPM refactorings receive zero instead of NaN.
top_200[["TH_count", "SPM_count"]] = (
    top_200[["TH_count", "SPM_count"]]
    .fillna(0)
    .astype(int)
)


# ---------------------------------------------------------------------------
# Prepare final dataset
# ---------------------------------------------------------------------------

# Pandas may preserve timezone information when reading the Parquet file.
# Excel does not support timezone-aware timestamps, so the timezone is
# removed before exporting.

if pd.api.types.is_datetime64tz_dtype(top_200["commit_time"]):
	top_200["commit_time"] = top_200["commit_time"].dt.tz_localize(None)


final_df = top_200[OUTPUT_COLUMNS].copy()


# ---------------------------------------------------------------------------
# Export
# ---------------------------------------------------------------------------

final_df.to_excel(
    OUTPUT_FILE,
    index=False,
)

print(f"Selected {len(final_df)} commits.")
print(f"Output written to: {OUTPUT_FILE}")
print(
    "Total refactorings in selected commits: "
    f"{final_df['refactoring_count'].sum():,}"
)